# Generated by Django 5.2.9 on 2025-12-09 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('main_image', models.ImageField(blank=True, help_text='الصورة الظاهرة في صفحة القائمة', null=True, upload_to='projects/main/')),
                ('is_featured', models.BooleanField(default=False, help_text='يظهر المشروع دايمًا في الأعلى')),
                ('priority', models.IntegerField(default=0, help_text='أرقام أقل تظهر في الأعلى (مثلاً: 1 هو الأعلى)')),
            ],
            options={
                'ordering': ['-is_featured', 'priority', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='ourproject.project')),
            ],
        ),
    ]
