# Generated by Django 5.2.9 on 2025-12-10 18:01

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-is_featured', 'priority', '-id'], 'verbose_name': 'مشروع', 'verbose_name_plural': 'المشاريع'},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'verbose_name': 'صورة إضافية', 'verbose_name_plural': 'معرض الصور'},
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='يظهر المشروع دايمًا في الأعلى', verbose_name='مميز؟'),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='الصورة الظاهرة في صفحة القائمة', max_length=255, null=True, verbose_name='الصورة الرئيسية'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم المشروع'),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.IntegerField(default=0, help_text='أرقام أقل = ظهور أعلى (مثل: 1 هو الأعلى)', verbose_name='أولوية الظهور'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='ourproject.project', verbose_name='المشروع'),
        ),
    ]
